### PR TITLE
575 design audit non critical

### LINKED ISSUE #575: design audit | Non Critical
This ticket tracks `Severity Rating: 1` items reported from the design audit 

https://docs.google.com/document/d/1DuIBVSXNBw8UmxvrZXEX8pb6MRklNw5vRYDpFLajux8/edit

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
## PR Summary

Updates design based on audit review.

https://docs.google.com/document/d/1Tgr4ccDpJjDVCTfXaRyqSpet-Fmv0bTD3qVX9_4F7v4/edit

## Related Github Issue

- fixes #575

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-c02462c4-7fff-14c8-8658-b67d96c2bfec"><div dir="ltr" style="margin-left:-44.25pt;" align="left">

46 | 9/11/2023 | Ernesto | Typefa Under Review ce | This is not a usability issue, it is just a design note. Severity Rating:1 https://drive.google.com/file/d/1ccCdboUF0IZ1r-MpJUnuJr52GZgmUs_M/view?usp=drive_link | Typeface is slightly different from Public Sans.Please see screenshot: right side image is MVP and left side image is Figma. |   | https://drive.google.com/file/d/1h9vi4OK5hyEQu63nlfITMg57ufh29b69/view?usp=drive_link | Design |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6809bbef-7fff-a3b2-0d8c-f2ed19e9d880"><div dir="ltr" style="margin-left:-44.25pt;" align="left">

51 | 9/11/2023 | Ernesto | Style notes: Horizontal line divider between Steps section and Button | This is not a usability issue, it is just a design note. Severity Rating:1 | Please take a look at the screenshot: the horizontal line is not necessary. |   | https://drive.google.com/file/d/15aKIpGSbf5ttTmMm-uqaGPwQjJ6dTSNT/view?usp=drive_link | Data Analytics | Blank Will backlog
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d58407be-7fff-40b6-8976-14d8337b1828"><div dir="ltr" style="margin-left:-44.25pt;" align="left">

53 | 9/13/23 | Ernesto | Spacing between subheading and drop down menus | Applicant’s relationship to the person who died (Required): the dropdown menu looks a bit too far from the heading.Severity Rating:1Marital status (Required): the dropdown menu looks a bit too far from the heading. |   |   | https://drive.google.com/file/d/180lrMqPZHdMbXGH92SKXXf7nHg8pCXdf/view?usp=drive_link | Design | Will be incorporated in a future release.
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-cd80a09b-7fff-c5c7-e5f6-709535020f69"><div dir="ltr" style="margin-left:-44.25pt;" align="left">

58 | 9/14/23 | Ernesto | 1White Space/ Negative space2 Question’s text in a single line & space between the radio buttons | 1This isn’t a usability issue. Just a cosmetic comment.Severity Rating: 12This isn’t a usability issue. Just a cosmetic comment.Severity Rating: 1 | 1There is a bit more negative space at the top and bottom of the form: above the status bar and under the CTAs.2On mock ups (left on the screenshot) questions are arranged in a single line, therefore they fill more space horizontally).I think if we follow the format from the MVP, then the whole form could be more narrow. | https://drive.google.com/file/d/1hLYKNtm-t5YvKTOA-HLcRF_VvS2SU7Tr/view?usp=drive_link | Blank | Design |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

60 - 3 | Radio buttons selected state is solid black vs blue with single white line (follows USWDS)
https://drive.google.com/file/d/1-1eMI2l2fNd5Az10vAv9R9qCJcqtVvJ0/view

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-8e33b5e6-7fff-6b9a-9433-fd68f866859c"><div dir="ltr" style="margin-left:-44.25pt;" align="left">

66 | 9/18/23 | Ernesto | CTA’S: order and size | This one could become a potential usability issue for people with disabilities as screen readers are reading the CTA’s in  a confusing order.Severity:2 + | Please take a look at the screenshot: we would like to change the cta’s to the example on the right: both buttons in a single line “back 1st, continue 2nd”Please apply change to mobile if needed: Back 1st, Continue 2nd”(See screenshot) |   | https://drive.google.com/file/d/1QPqJAfbLQpAc7cTmjpVbeLQM4HhM0sZa/view?usp=drive_linkhttps://drive.google.com/file/d/1e_Eagw72lkPY2cYWbxDiw5whIWoP86ko/view?usp=drive_link | Design | Under ReviewFlagging this one, recommended change to the MVP
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-912f9ed7-7fff-279b-3da5-759bcce01723"><div dir="ltr" style="margin-left:-44.25pt;" align="left">

68 | 9/18/23 | Ernesto | Blank Modal | 1To be consistent with other button size changes recommended, buttons on modal are also changed to smaller size (as mobile)Note: button size change requested by client.Severity:1, not a usability issue2Typeface for “Select an option” design uses 16px (paragraph font size)Severity:1, not a usability issue3Checkmark icon missingSeverity:1, not a usability issue | 1Please take a look at the screenshot: image on the right shows updated buttons.2Please take a look at the screenshot: image on the right shows the correct font.2Please take a look at the screenshot: image on the right shows the icon. |   | https://drive.google.com/file/d/1z9nuiGQ544qqZddnIAQaiglWk3t8r67X/view?usp=drive_link | Data Analytics |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

78 - 2
We separated this into a Heading and a Subheading

Key Eligibility Criteria uses Bold 16 (Public Sans)
Meet 4 of 4 uses Regular 16 (Public Sans)

</div></b>

</div></b>

</div></b>

</div></b>

</div></b>

</div></b>

</div></b>

## Detailed Testing steps

Link to testing steps in the issue or list them here:

- [ ] see comments above

### CODE REVIEW

**Comment by nehemiah-abuga** [comment]
@scottqueen-bixal  - For the radio buttons, the currently highlighted radio button has an orange circle around it. Is that intended?
image

**Review by nehemiah-abuga — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Comment by scottqueen-bixal** [comment]
> @scottqueen-bixal - For the radio buttons, the currently highlighted radio button has an orange circle around it. Is that intended? image

when we are on USA gov site we should see the orange outline on focused elements

**Review by nehemiah-abuga — APPROVED** [review]
I have reviewed the changes on this ticket and everything looks good. Approved

**Pull request merged**
